default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "database") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "stream_app") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "stream_app") %>_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "stream_app") %>_production
  cache:
    <<: *primary_production
    database: stream_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: stream_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: stream_app_production_cable
    migrations_paths: db/cable_migrate
