services:
  frontend:
    image: node:22.14.0
    container_name: frontend
    working_dir: /frontend
    depends_on:
      - backend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/frontend
    command: bash -c "npm install && npm run dev"

  backend:
    image: ruby:3.4.2
    container_name: backend
    working_dir: /backend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - gems_data:/usr/local/bundle
      - ./backend:/backend
    command: bash -c "bundle && bin/setup"

  database:
    image: postgres:17-alpine
    container_name: database
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
  gems_data:
